### ISSUE TITLE
点击图片后的跳转，怎么实现？

### ISSUE THREAD

**Issue by ecshoptpl** [zhangsuya/SYStickHeaderWaterFall#2]
有代理吗？

**Comment by zhangsuya** [comment]
如果是点击整块item跳转的话，调用UICollectionViewDelegate里的代理方法：
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath;
  如果只是点击图片跳转的话，为图片加一个手势事件就可以了。
