### ISSUE TITLE
关于collectionView刷新的问题

### ISSUE THREAD

**Issue by QianNan** [zhangsuya/SYStickHeaderWaterFall#8]
1，      MJRefresh对collectionView进行分页加载，为什么有时候数据刷新出来，但是cell的数据没有加载出来。reloadata有时有效，有时无效。首先确定调用接口后的数组数据已增加，但是reloadata页面没有出来。

2，疑问：为什么要把delegte和datasorce写在数据请求接口中而不是viewDidLoad中

3，疑问：重写父类的prepareLayout，不用添加 [super prepareLayout];  这句吗？  

```
为什么要在滚动的时候不用重新布局呢？
if (self.collectionView.isDecelerating || self.collectionView.isDragging) {

} else {   }
```

  我的代码中需要分页加载，在重写的父类方法中 把这部分注释掉，添加  [super prepareLayout]; 就可以分页加载数据不会漏掉了。

原因不明白，提出来希望可以有人解答

**Comment by zhangsuya** [comment]
下面123对应问题的123.
1.请确保reloadData方法在主线程中运行。
2.delegate和datasource放在请求接口里，纯粹是为了保证请求完成之前不去执行reloadData。这中写法并不好，不建议您去使用这种方法。
3.您提到了的这点很有意思，我会在研究研究

**Comment by QianNan** [comment]
求教：在代码中把SYStickHeaderWaterFallLayout 布局更换为系统的FlowLayout布局，为什么delegate和dataSource无效，应用启动后直接卡在启动页面不动。如果更换为SYStickHeaderWaterFallLayout 布局，一切正常执行。当然flowLayout的代理方法都已经实现了，单独做了测试是有效的。

**Comment by QianNan** [comment]
代码布局问题，已修改，打扰了
